from fpdf import FPDF
from datetime import datetime

def clean_text(text):
    lines = text.split("\n")
    lines = [line for line in lines if not line.startswith("#")]
    text = "\n".join(lines)
    text = text.replace("\u2014", "-")
    text = text.replace("\u2013", "-")
    text = text.replace("\u2018", "'")
    text = text.replace("\u2019", "'")
    text = text.replace("\u201c", '"')
    text = text.replace("\u201d", '"')
    text = text.replace("\u2022", "-")
    text = text.encode("latin-1", "replace").decode("latin-1")
    return text.strip()

def generate_report(all_findings):
    pdf = FPDF()
    pdf.add_page()

    pdf.set_font("Arial", "B", 28)
    pdf.cell(0, 20, "BiasLens", ln=True, align="C")
    pdf.set_font("Arial", "", 16)
    pdf.cell(0, 10, "Hiring Bias Detection Report", ln=True, align="C")
    pdf.ln(10)

    pdf.set_font("Arial", "", 12)
    pdf.cell(0, 10, f"Generated on: {datetime.now().strftime('%B %d, %Y')}", ln=True, align="C")
    pdf.ln(15)

    pdf.set_font("Arial", "", 12)
    pdf.multi_cell(0, 8, "This report was generated by BiasLens, a hiring bias detection tool. It analyzes hiring data using the 80% rule for disparate impact to identify demographic groups that may be facing unfair treatment in the hiring process. Each finding includes an AI-generated plain-English explanation.")
    pdf.ln(10)

    total_groups = len(all_findings)
    biased_groups = len([f for f in all_findings if f["bias_detected"]])
    no_bias_groups = total_groups - biased_groups
    demographic_cols = set(f["demographic_col"] for f in all_findings)

    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "Summary", ln=True)
    pdf.set_font("Arial", "", 12)
    pdf.cell(0, 8, f"Demographic categories analyzed: {len(demographic_cols)}", ln=True)
    pdf.cell(0, 8, f"Total groups analyzed: {total_groups}", ln=True)
    pdf.cell(0, 8, f"Groups with bias detected: {biased_groups}", ln=True)
    pdf.cell(0, 8, f"Groups with no bias: {no_bias_groups}", ln=True)
    pdf.ln(10)

    if biased_groups > 0:
        pdf.set_font("Arial", "B", 14)
        pdf.cell(0, 10, "Flagged Groups", ln=True)
        pdf.set_font("Arial", "", 12)
        for finding in all_findings:
            if finding["bias_detected"]:
                pdf.cell(0, 8, f"- {finding['group']} ({finding['demographic_col']}) - Success rate: {finding['rate']}%", ln=True)
        pdf.ln(10)

    for col in demographic_cols:
        pdf.add_page()
        pdf.set_font("Arial", "B", 18)
        pdf.cell(0, 15, f"Analysis: {col.title()}", ln=True)
        pdf.ln(5)
        pdf.image(f"chart_{col}.png", x=10, w=180)
        pdf.ln(10)
        for finding in all_findings:
            if finding["demographic_col"] == col:
                pdf.set_font("Arial", "B", 14)
                pdf.cell(0, 10, f"{finding['group']} ({finding['demographic_col']})", ln=True)
                pdf.set_font("Arial", "", 12)
                pdf.multi_cell(0, 8, clean_text(finding["explanation"]))
                pdf.ln(5)

    pdf.output("report.pdf")